inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
